/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_ndk_NDKDemo */

#ifndef _Included_com_study_ndk_NDKDemo
#define _Included_com_study_ndk_NDKDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_ndk_NDKDemo
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_study_ndk_NDKDemo_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
